/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_akhir_trisari;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armann
 */
public class rt22 extends javax.swing.JFrame {

    String nomor, nama, jumlah, ekonomi,id;
    static Connection conn;
    static Statement stmt;
    static ResultSet rs; 
    
     public void tampil(){
        try{
            connect connect = new connect();
             conn=(Connection)connect.DB();
             String sql = "SELECT * FROM rt22";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
              DefaultTableModel model = new DefaultTableModel();
                 model.addColumn("No. Rumah");
                 model.addColumn("Kepala Keluarga");
                 model.addColumn("Jumlah Anggota");
                 model.addColumn("Golongan");
                 model.addColumn("Agama");
                 model.addColumn("RT");
              int no = 1;
              while(rs.next()){
                 model.addRow(new Object[] {rs.getString("nomor"), rs.getString("nama"), rs.getString("jumlah"), rs.getString("golongan"), rs.getString("agama"), rs.getString("rt")});
              }
              warga1.setModel(model);
              warga1.setShowGrid(true);
              warga1.getColumnModel().getColumn(0).setPreferredWidth(90);
              warga1.getColumnModel().getColumn(1).setPreferredWidth(120);
              warga1.getColumnModel().getColumn(2).setPreferredWidth(100);
              warga1.getColumnModel().getColumn(3).setPreferredWidth(85);
              warga1.getColumnModel().getColumn(4).setPreferredWidth(70);
              warga1.getColumnModel().getColumn(5).setPreferredWidth(50);
              warga1.setRowHeight(30);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
     
     void hapus(){
         nomorRumah1.setText(null);
         namaKeluarga1.setText(null);
         jumlahKeluarga1.setText(null);
         cbgolongan1.setSelectedItem(this);
     }
     
    public rt22() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nomorRumah1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        namaKeluarga1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jumlahKeluarga1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbgolongan1 = new javax.swing.JComboBox<>();
        tambah1 = new javax.swing.JButton();
        perbarui1 = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        warga1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        rt21 = new javax.swing.JButton();
        rt25 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        agamaTxt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Data Warga Trisari");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nama Kepala Keluarga");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nomor Rumah");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Jumlah Anggota Keluarga");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Golongan Ekonomi");

        cbgolongan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kaya", "Mampu", "Kurang Mampu" }));

        tambah1.setText("Tambah Data");
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });

        perbarui1.setText("Perbarui Data");
        perbarui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbarui1ActionPerformed(evt);
            }
        });

        hapus1.setText("Hapus Data");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        warga1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Rumah", "Kepala Keluarga", "Jumlah Anggota", "Golongan Ekonomi"
            }
        ));
        warga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                warga1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(warga1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("RT 22");

        menu1.setText("Menu Utama");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        rt21.setText("Data RT. 21");
        rt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rt21ActionPerformed(evt);
            }
        });

        rt25.setText("Data RT. 23");
        rt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rt25ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Agama");

        agamaTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindhu", "Buddha" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomorRumah1)
                                        .addComponent(namaKeluarga1)
                                        .addComponent(jumlahKeluarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbgolongan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rt21)
                                    .addComponent(tambah1))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menu1)
                                    .addComponent(perbarui1))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hapus1)
                                    .addComponent(rt25))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel12)))
                        .addContainerGap(426, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomorRumah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaKeluarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jumlahKeluarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbgolongan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah1)
                            .addComponent(hapus1)
                            .addComponent(perbarui1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menu1)
                            .addComponent(rt21)
                            .addComponent(rt25)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        String nama = namaKeluarga1.getText();
        String nomor = nomorRumah1.getText();
        String jumlah = jumlahKeluarga1.getText();
        String golongan = cbgolongan1.getSelectedItem().toString();
        String agama = agamaTxt.getSelectedItem().toString();
        String rt = "22";
        boolean betul = false;
        if (nama.isEmpty() | nomor.isEmpty() | jumlah.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
            hapus();
        }
        else{
            try{
                connect connect = new connect();
                conn=(Connection)connect.DB();
                String sql1 = "SELECT * FROM rt22";
                rs = stmt.executeQuery(sql1);
                //             verifikasi jika ada data yang sama
                while(rs.next()){
                    String namaDB = rs.getString("nama");
                    String nomorDB = rs.getString("nomor");
                    if (nama.equals(namaDB)||nomor.equals(nomorDB)){
                        betul = true;
                        break;
                    }
                    else{
                        betul = false;
                    }
                }
                if(betul == true){
                    JOptionPane.showMessageDialog(null, "Nomor Rumah atau Nama sudah ada");
                    hapus();
                }
                if(betul == false){

                    stmt = conn.createStatement();
                    
                    String sql = "INSERT INTO `rt22`(`nomor`, `nama`, `jumlah`, `golongan`, `agama`, `rt`) VALUES ('%s','%s','%s','%s','%s','%s')";
                    sql = String.format(sql, nomor, nama, jumlah, golongan, agama, rt);
                    stmt.execute(sql);
                    JOptionPane.showMessageDialog(null, "DATA BERHASIL DITAMBAHKAN");
                    tampil();
                    hapus();

                }

            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tambah1ActionPerformed

    private void perbarui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbarui1ActionPerformed
        String nama = namaKeluarga1.getText();
        String nomor = nomorRumah1.getText();
        String jumlah = jumlahKeluarga1.getText();
        String agama = agamaTxt.getSelectedItem().toString();
        if(nama.isEmpty() | nomor.isEmpty() | jumlah.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong");
            hapus();
        }
        else{
            try{
                connect connect = new connect();
                conn=(Connection)connect.DB();
                stmt = conn.createStatement();
                String golongan = cbgolongan1.getSelectedItem().toString();
                String sql = "UPDATE rt22 SET nomor='%s',nama='%s',jumlah='%s',golongan='%s',agama='%s'  WHERE nomor=%s";
                sql = String.format(sql, nomor, nama, jumlah, golongan,agama, id);
                stmt.execute(sql);
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIPERBARUI");
                tampil();
                hapus();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_perbarui1ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        try{
            connect connect = new connect();
            conn=(Connection)connect.DB();
            stmt = conn.createStatement();
            String nama = namaKeluarga1.getText();
            String golongan = cbgolongan1.getSelectedItem().toString();
            String sql = "DELETE FROM `rt22` WHERE nomor = '%s'";
            sql = String.format(sql, id);
            stmt.execute(sql);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
            tampil();
            hapus();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void warga1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warga1MouseClicked
        int baris = warga1.rowAtPoint(evt.getPoint());
        id = warga1.getValueAt(baris, 0).toString();
        nomorRumah1.setText(id);
        nama = warga1.getValueAt(baris, 1).toString();
        namaKeluarga1.setText(nama);
        jumlah = warga1.getValueAt(baris, 2).toString();
        jumlahKeluarga1.setText(jumlah);
        ekonomi = warga1.getValueAt(baris, 3).toString();
        cbgolongan1.setSelectedItem(ekonomi);
    }//GEN-LAST:event_warga1MouseClicked

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu1ActionPerformed

    private void rt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rt21ActionPerformed
        rt21 rt21 = new rt21();
        rt21.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rt21ActionPerformed

    private void rt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rt25ActionPerformed
       rt23 rt23 = new rt23();
       rt23.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_rt25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rt22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rt22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rt22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rt22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rt22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agamaTxt;
    private javax.swing.JComboBox<String> cbgolongan1;
    private javax.swing.JButton hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahKeluarga1;
    private javax.swing.JButton menu1;
    private javax.swing.JTextField namaKeluarga1;
    private javax.swing.JTextField nomorRumah1;
    private javax.swing.JButton perbarui1;
    private javax.swing.JButton rt21;
    private javax.swing.JButton rt25;
    private javax.swing.JButton tambah1;
    private javax.swing.JTable warga1;
    // End of variables declaration//GEN-END:variables
}
